apiVersion: v1
kind: Service
metadata:
  name: {{ include "banksystem-demoshop.fullname" . }}
  labels:
    {{- include "banksystem-demoshop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "banksystem-demoshop.selectorLabels" . | nindent 4 }}
