apiVersion: v1
kind: Service
metadata:
  name: {{ include "banksystem-centralapi.fullname" . }}
  labels:
    {{- include "banksystem-centralapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort.port }}
      protocol: TCP
  selector:
    {{- include "banksystem-centralapi.selectorLabels" . | nindent 4 }}
