# The name of the application
application: barista-val-cafe
clusterConfig:
  namespace: barista-val-cafe
  name: barista-val-cafe
  
# Number of replicas to deploy
replicaCount: 2

# Image configuration
image:
  registry: 485797251250.dkr.ecr.eu-west-1.amazonaws.com
  repository: barista-val-cafe
  tag: "" # Overrides the image tag, Defaults to the chart AppVersion
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameoveride: ""
fullnameOverride: ""

# Service configuration
serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # enabled: true
  #fsGroup: 2000
  # capabilities:
  #  drop:
  #    - ALL
  # readOnlyRootFilesystem: true
  # runAsUser: 1000

# Service configuration
service:
  name: barista-val-cafe
  type: ClusterIP
  port: 80
  targetPort: 80

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/tsl-acme: "true"
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: barista-val-cafe.radiantcommons.com
      paths:
       - path: /
         pathType: ImplementationSpecific
  tls: []
  # - secretName: barista-val-cafe-tls
  #   hosts:
  #     - barista-val-cafe.radiantcommons.com
  
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

resources: {}
  # limits:
  # cpu: 100m
  # memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# NodeSelector configuration
nodeSelector: {}

tolerations: []

affinity: {}

existingSecret:
name: "barista-val-cafe"  
  # secretName: barista-val-cafe-tls
