{{- if eq .Values.workloadType "statefulset" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffee-ae-service.fullname" . }}-headless
  labels:
    {{- include "coffee-ae-service.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "coffee-ae-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
