{{- if eq .Values.workloadType "statefulset" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "coffee-ae-service.fullname" . }}
  labels:
    {{- include "coffee-ae-service.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "coffee-ae-service.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "coffee-ae-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "coffee-ae-service.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "coffee-ae-service.serviceAccountName" . }}

      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: data-storage
              mountPath: /app/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
    {{- toYaml .Values.volumeClaimTemplates | nindent 4 }}
{{- end }}
