{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "penumbra-analytics-service.fullname" . }}-secret
  labels:
    {{- include "penumbra-analytics-service.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}