---
# Custom values for the NEW Penumbra indexer node with fresh RDS database
application: penumbra-indexer-node-new
clusterConfig:
  namespace: penumbra

image:
  repository: ghcr.io/penumbra-zone/penumbra
  tag: "v2.0.0"
  pullPolicy: IfNotPresent

penumbra_bootstrap_node_cometbft_rpc_url: "http://void.s9.gay:26657"

penumbra_bootstrap_archive_url: "https://artifacts.plinfra.net/penumbra-1/penumbra-node-archive-height-5830749.tar.gz"

cometbft:
  image:
    repository: cometbft/cometbft
    tag: "v0.37.15"
    pullPolicy: IfNotPresent
  securityContext:
    runAsUser: 101
    runAsGroup: 1000
  config:
    p2p:
      max_num_inbound_peers: 300
      max_num_outbound_peers: 200
      seeds: >
        c28827cb96c14c905b127b92065a3fb4cd77d7f6@seeds.whispernode.com:21956,
        20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:21956
      persistent_peers: >
        7ae6236905eb6a06d9f27e22204d4c49d4e36d4f@108.21.128.181:26656,
        76a0f3a7dbc735bd799a8630dfe21ef932816ba3@159.89.254.147:26656
    fast_sync: true
    addr_book_strict: false
    indexer: psql
    postgres_connection_url: "postgresql://pindexerdb:19Ab94cd1994@pindexerdb.cfu6kcq4ezl6.eu-west-1.rds.amazonaws.com:5432/indexer"
    instrumentation:
      prometheus: true
      prometheus_listen_addr: ":26660"
      max_open_connections: 3
      namespace: "tendermint"

postgres: {}

containerEnv: []

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

wait_for_catchup: false
maintenanceMode: false
ingressRoute:
  enabled: false

ingress:
  enabled: false

grpcIngress:
  enabled: false

persistence:
  enabled: true
  size: 500Gi
  storageClassName: ovh-block-standard
  db:
    size: 50Gi

nodes:
  - moniker: rc-penumbra-indexer-node-new
    external_address: ""
    seed_mode: false

part_of: rc-penumbra
