apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "penumbra-lqt-bot.fullname" . }}-config
  labels:
    {{- include "penumbra-lqt-bot.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
