{{- if .Values.ingress.enabled -}}
{{- $fullName := include "penumbra-node.fullname" . -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: penumbra-rpc-ingress
  labels:
    {{- include "penumbra-node.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- else if (and .Values.ingress.hosts .Values.ingress.annotations) }}
  tls:
    - hosts:
        - {{ (index .Values.ingress.hosts 0).host | quote }}
      secretName: {{ $fullName }}-rpc-tls
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-0
                port:
                  name: tm-rpc
    {{- end }}
---
{{- if .Values.grpcIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: penumbra-grpc-ingress
  labels:
    {{- include "penumbra-node.labels" . | nindent 4 }}
  {{- with .Values.grpcIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.grpcIngress.tls }}
  tls:
    {{- range .Values.grpcIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- else if (and .Values.grpcIngress.host .Values.grpcIngress.annotations) }}
  tls:
    - hosts:
        - {{ .Values.grpcIngress.host | quote }}
      secretName: {{ $fullName }}-grpc-tls
  {{- end }}
  rules:
    - host: {{ .Values.grpcIngress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-0
                port:
                  name: pd-grpc
{{- end }}
{{- end }}
