apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cleanwork-va-service.fullname" . }}
  labels:
    {{- include "cleanwork-va-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cleanwork-va-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cleanwork-va-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cleanwork-va-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry | default "" }}{{ if .Values.image.registry }}/{{ end }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
           httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {{- toYaml .Values.resources | nindent 12 }}
            # Penumbra specific env variables
           # {{- if .Values.existingSecret.name }}
            #- name: PENUMBRA_GRPC_ENDPOINT
             # valueFrom:
              #  secretKeyRef:
               #   name: {{ .Values.existingSecret.name }}
            #      key: PENUMBRA_GRPC_ENDPOINT
           # - name: PENUMBRA_INDEXER_ENDPOINT
             # valueFrom:
               # secretKeyRef:
              #    name: {{ .Values.existingSecret.name }}
             #     key: PENUMBRA_INDEXER_ENDPOINT
            #- name: PENUMBRA_INDEXER_CA_CERT
              #valueFrom:
               # secretKeyRef:
              #    name: {{ .Values.existingSecret.name }}
             #     key: PENUMBRA_INDEXER_CA_CERT
            #- name: PENUMBRA_CHAIN_ID
             # valueFrom:
               # secretKeyRef:
              #    name: {{ .Values.existingSecret.name }}
             #     key: PENUMBRA_CHAIN_ID
            #- name: PENUMBRA_CUILOA_URL
              #valueFrom:
             #   secretKeyRef:
            #      name: {{ .Values.existingSecret.name }}
           #       key: PENUMBRA_CUILOA_URL
           # {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}