apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: veil-service-externalsecret
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: secret-store-name # Your ESO secret store
    kind: SecretStore
  target:
    name: veil-service-secrets # Set this name in values.yaml as existingSecret.name
    creationPolicy: Owner
  data:
    - secretKey: PENUMBRA_GRPC_ENDPOINT
      remoteRef:
        key: your/secret/path
        property: penumbra_grpc_endpoint
    - secretKey: PENUMBRA_INDEXER_ENDPOINT
      remoteRef:
        key: your/secret/path
        property: penumbra_indexer_endpoint
    - secretKey: PENUMBRA_INDEXER_CA_CERT
      remoteRef:
        key: your/secret/path
        property: penumbra_indexer_ca_cert
    - secretKey: PENUMBRA_CHAIN_ID
      remoteRef:
        key: your/secret/path
        property: penumbra_chain_id
    - secretKey: PENUMBRA_CUILOA_URL
      remoteRef:
        key: your/secret/path
        property: penumbra_cuiloa_url