apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      managed-by: prometheus-operator
      operated-prometheus: "true"
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http-web
      path: /metrics
      interval: 30s
      scheme: http
